platform :ios, "14.0"

source "https://github.com/Allegion-Plc/AllegionCocoaPods"
source "https://cdn.cocoapods.org/"

use_frameworks!

target "BrivoSampleApp" do
    pod "Allegion.Access.MobileAccessSDK.iOS", "~> 4.0.0"
end

post_install do |installer|
  remove_allegion_duplicate_static_linkage(['Pods-BrivoSampleApp'], installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ""
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "14.0"
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

    end
  end
end

def remove_allegion_duplicate_static_linkage(app_targets, installer)
  installer.aggregate_targets.each do |target|
    if app_targets.include?(target.name) then
      target.xcconfigs.each do |config_name, config_file|
        config_file.frameworks.delete('AllegionAnalytics')
        config_file.frameworks.delete('Allegion_Access_MobileAccessSDK_iOS')
        config_file.frameworks.delete('AppCenter')
        config_file.frameworks.delete('AppCenterAnalytics')
        config_file.frameworks.delete('AppCenterCrashes')
        xcconfig_path = target.xcconfig_path(config_name)
        config_file.save_as(xcconfig_path)
      end
    end
  end
end
